apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lan-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.17.128.79-172.17.128.79   
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lan-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - lan-pool
#kubectl apply -f metallb-ip-pool.yaml
#kubectl -n metallb-system get ipaddresspools
#kubectl -n metallb-system get l2advertisements
